export const dataRoom = [
    {
        id: 1,
        name: 'Phòng 111',
        type: "Phòng thường",
        prices: '200000',
        bad: '01 giường đơn',
        limitedPer: '2 người lớn, 1 trẻ em',
        s: '25m²',
        huong:' Nhìn ra vườn',
        baoGom: 'Bữa sáng+ dịch vụ',
        image: 'https://media.vneconomy.vn/w800/images/upload/2022/07/27/khach-san-5-sao-da-nang.jpg',
      },
      {
        id: 1,
        name: 'Phòng 111',
        prices: '200000',
        bad: 1,
        limitedPer: '2 người lớn, 1 trẻ em',
        s: '35m²',
        huong:' nhìn ra thành phố',
        baoGom: 'Bữa sáng+ dịch vụ',
        image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_1000/v1627034532/blog/ulhhahezsa1zahjtpmdm.webp',
      },
]